/**:
  ros__parameters:
    min_longitudinal_offset: 2.0
    max_longitudinal_offset: 2.21
    min_lateral_offset: 0.96
    max_lateral_offset: 1.25
    min_height_offset: 0.96
    max_height_offset: 1.10
