/**:
  ros__parameters:
    wheel_radius: 0.330 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.127 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.82 # between front wheel center and rear wheel center
    wheel_tread: 1.64 # between left wheel center and right wheel center
    front_overhang: 1.37 # between front wheel center and vehicle front
    rear_overhang: 1.17 # between rear wheel center and vehicle rear
    left_overhang: 0.41 # between left wheel center and vehicle left
    right_overhang: 0.41 # between right wheel center and vehicle right
    vehicle_height: 1.45 # This values is excluding the LiDAR,i.e. only until the roof of Lincoln
    max_steer_angle: 0.70 # [rad]
